"""create db

Revision ID: 6d99ddde14ad
Revises: a97892b578a8
Create Date: 2022-01-13 13:40:16.171008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d99ddde14ad'
down_revision = 'a97892b578a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
